name: Playwright
on: [workflow_dispatch]

jobs:
    playwright:
        runs-on: self-hosted

        strategy:
            matrix:
                node-version: [16.x]

        steps:
            - uses: actions/setup-node@v3

            - name: Update tui
              run: npm install --global cafe-tui

            - name: Download test source
              run: npx cafe-tui get-unzip https://github.com/Cafe137/nimbus/archive/refs/heads/master.zip .

            - name: Download desktop source
              run: npx cafe-tui get-unzip https://github.com/ethersphere/swarm-desktop/archive/refs/heads/master.zip .

            - name: Install UI dependencies
              working-directory: ./swarm-desktop-master/ui
              run: npm install

            - name: Install desktop dependencies
              working-directory: ./swarm-desktop-master
              run: npm install

            - name: Start Xvfb
              run: Xvfb :1 -screen 0 1024x768x24 &

            - name: Start desktop
              working-directory: ./swarm-desktop-master
              run: DISPLAY=:1 NODE_ENV=development npm start &

            - name: Wait for bee to listen
              run: npx cafe-tui await-port 1633

            - name: Wait for desktop to serve dashboard
              run: npx cafe-tui await-port 3002 dashboard

            - name: Install test dependencies
              working-directory: ./nimbus-master
              run: npm install

            - name: Run playwright
              working-directory: ./nimbus-master
              run: DISPLAY=:1 npm start

            - name: Kill desktop
              run: killall node
